
export const CSV_DATA_LIVE = `First Name,Last Name,Email,Phone Number,Title,LinkedIn,Company,Employees,Revenue,Country,Industry,Asset Downloaded,What pain drives your interest in migrating to the cloud?,Which aspect of your cloud strategy are you most looking to optimize?,Which AWS solutions do you currently have installed or in use? (Select all that apply),Would you be open to learning more from an Ingram Micro professional?,Email 1,Email 2,Email 3,Cold Call,Internal Team Member Asigned,Partner Assigned,
David,Hildebrand,dhildebrand@slmhc.on.ca,18077379181,Director of Information Technology & Information Systems,https://www.linkedin.com/in/dave-hildebrand/,Sioux Lookout Meno Ya Win Health Centre,201-500,10M-100M,Canada,Healthcare / Medical,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,We do not currently use any AWS solutions,Not at this time,TRUE,FALSE,FALSE,FALSE,Sakal,HabileLabs,
Jivan,Maharaj,jmaharaj@olympic.ca,14163244137/+1 647-390-7975,IT Director,https://www.linkedin.com/in/jivanmaharaj/?originalSubdomain=ca,Canadian Olympic Committee,51-200,10M-100M,Canada,Non-Profit / Organizations,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,AWS Lambda,"Yes, by email",TRUE,TRUE,FALSE,TRUE,Sakal,HabileLabs,
Moheb,Ekladios,moheb.ekladios@cvc.ca,14169189801,CIO,https://www.linkedin.com/in/mekladios/,Credit Valley Conservation,201-500,10M-100M,Canada,Non-Profit / Organizations,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Resource provisioning,We do not currently use any AWS solutions,"Yes, by email",TRUE,TRUE,FALSE,TRUE,Sakal,HabileLabs,
Daniel,Mizrahi,dmizrahi@ontariospca.ca,14166185391,"Director, IT Systems",https://www.linkedin.com/in/dmizrahi/?f_s=true,Ontario SPCA & Humane Society,201-500,10M-100M,Canada,Non-Profit / Organizations,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Risk and compliance management,AWS Lambda,"Yes, by email",TRUE,TRUE,FALSE,TRUE,Sakal,HabileLabs,
Jonathan,Gagne,jgagne@sbi-international.com,14185757724,Director of IT,https://www.linkedin.com/in/jonathan-gagn%C3%A9-62605624/?f_s=true,SBI Stove Builder InternationalInternatioInternat,201-500,10M-100M,Canada,Manufacturing,Maximiser les économies et la performance,Limited scalability with our current data infrastructure,Cost control,Amazon S3,Not at this time,TRUE,TRUE,FALSE,TRUE,Sakal,HabileLabs,
Razvan,Anghelidi,ranghelidi@signifi.com,16477083941,Director of IT,https://www.linkedin.com/in/razvan-anghelidi-0564274/?originalSubdomain=ca,"Signifi Solutions, Inc.",51-200,10M-100M,Canada,Computers and Technology,Maximize Savings and Performance,Limited scalability with our current data infrastructure,Cost control,We do not currently use any AWS solutions,"Yes, by email",TRUE,TRUE,FALSE,FALSE,Subbu,Ingeno,
Mohamad,El Bakri,mohamad.elbakri@entegrus.com,15198710769,"Director of Information TechnologyIT service management, operations, and infrastructure",https://www.linkedin.com/in/melbakri/,Entegrus,51-200,10M-100M,Canada,Utility / Energy,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Data accessibility and storage,We do not currently use any AWS solutions,"Yes, by email",TRUE,TRUE,FALSE,TRUE,Subbu,Ingeno,
Thierry,Aubin,t.aubin@mirabel.ca,14504758653,Head of Information Technology Administration,https://www.linkedin.com/in/thierry-aubin-6a943537/?originalSubdomain=ca,Ville De Mirabel,51-200,10M-100M,Canada,Government,Maximiser les économies et la performance,Cost and complexity of maintaining legacy solutions,Cost control,We do not currently use any AWS solutions,Not at this time,FALSE,FALSE,FALSE,FALSE,Subbu,Ingeno,
Max,Goulet,max.goulet@ferique.com,15146493489,Vice President Technologies,https://www.linkedin.com/in/maxgoulet-ing-cfa/,FERIQUE,51-200,10M-100M,Canada,Finance,Maximiser les économies et la performance,Limited scalability with our current data infrastructure,Cost control,Amazon S3,"Yes, by email",TRUE,TRUE,FALSE,FALSE,Subbu,Ingeno,
Jean-Francois,L'Heureux,jlheureux@getfishtank.ca,14189259151,Director of Technology,https://www.linkedin.com/in/jflheureux/,Fishtank Consulting,51-200,1-10M,Canada,Computers and Technology,Maximiser les économies et la performance,Difficulty keeping up with evolving data security regulations,Cost control,We do not currently use any AWS solutions,Not at this time,TRUE,TRUE,FALSE,TRUE,Subbu,Ingeno,
Kristian,Bowie,kbowie@unitedwayeo.ca,16132774300,Chief Information and Technology Officer,https://www.linkedin.com/in/kristian-bowie-3691609/?f_s=true,United Way East Ontario,51-200,10M-100M,Canada,Non-Profit / Organizations,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,We do not currently use any AWS solutions,Not at this time,TRUE,TRUE,FALSE,FALSE,Gautam,Coulter Software,
Neil,Hopson,neilhopson@daleservices.on.ca,15196718142,Director of HR & Information Systems,https://www.linkedin.com/in/neil-hopson-9237473/?originalSubdomain=ca,Dale Brain Injury Services,51-200,10M-100M,Canada,Healthcare / Medical,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Data accessibility and storage,We do not currently use any AWS solutions,Not at this time,TRUE,TRUE,FALSE,FALSE,Gautam,Coulter Software,
Murthy S,Challa,mchalla@bulldogbag.com,18006651944,Chief Information Officer,https://www.linkedin.com/in/murthy-s-challa-5b361132/?originalSubdomain=ca,"Bulldog Bag, LTD",201-500,10M-100M,Canada,Manufacturing,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,We do not currently use any AWS solutions,Not at this time,TRUE,TRUE,FALSE,FALSE,Gautam,Coulter Software,
Mauricio,Briceno,mauricio.briceno@organigram.ca,16474094815,Director Of It Operations,https://www.linkedin.com/in/bricenom/,Organigram Global,"1,001-5,000",100M-500M,Canada,Manufacturing,Maximize Savings and Performance,Limited scalability with our current data infrastructure,Cost control,Other (please specify),"Yes, by email",TRUE,TRUE,FALSE,TRUE,Gautam,Coulter Software,
Etienne,Bedard,etienne.bedard@parl.gc.ca,16139445114,"Director, Digital Enterprise Strategy",https://www.linkedin.com/in/%C3%A9tienne-b%C3%A9dard-a8b48aa4/?originalSubdomain=ca,House Of Commons Of Canada,"1,001-5,000",100M-500M,Canada,Government,Maximize Savings and Performance,Difficulty keeping up with evolving data security regulations,Risk and compliance management,We do not currently use any AWS solutions,Not at this time,TRUE,TRUE,FALSE,FALSE,Gautam,Coulter Software,
Catalin,Petria,cpetria@tempo.io,15143468595,Director of IT,https://www.linkedin.com/in/catalin-petria/,Tempo Software,201-500,10M-100M,Canada,Computers and Technology,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,All AWS solutions useing,"Yes, by email",TRUE,FALSE,FALSE,FALSE,Sakal,,
Serge,Tremblay,serge.tremblay@inrs.ca,14186542516,Director of Information Resources,https://www.linkedin.com/in/serge-tremblay-19146429/?originalSubdomain=ca,Institut National De La Recherche Scientifique,51-200,1-10M,Canada,Education,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,Amazon EC2,Not at this time,TRUE,FALSE,FALSE,FALSE,Sakal,,
Alain,Boivin,alain.boivin@cogiweb.com,14188054857,Director Information and Communications Technologies,https://www.linkedin.com/in/alain-boivin-44741a26/?originalSubdomain=ca,COGIWEB,51-200,10M-100M,Canada,Computers and Technology,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,We do not currently use any AWS solutions,"Yes, by email",TRUE,FALSE,FALSE,FALSE,Subbu,Ingeno,
Mathieu,Lapointe,mlapointe@wild-blueberries.com,14183432206,Head of Information Technology,https://www.linkedin.com/in/lapointe-mathieu/,Quebec Wild Blueberry Group Freezing Plants,201-500,10M-100M,Canada,Manufacturing,Maximize Savings and Performance,Limited scalability with our current data infrastructure,Risk and compliance management,We do not currently use any AWS solutions,"Yes, by email",FALSE,FALSE,FALSE,FALSE,Subbu,Ingeno,
Remy,Cote,rcote@entrepotsab.ca,14504350725,IT Director,https://www.linkedin.com/in/r%C3%A9my-c%C3%B4t%C3%A9-6545167/,AB Warehouse,51-200,1-10M,Canada,Transportation and Logistics,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Cost control,Azure,"Yes, by email",TRUE,FALSE,TRUE,FALSE,Gautam,Coulter Software,
Jayson,Byrne,jayson@dfbarnes.com,17097266820,"Director, Information Communication Technology",https://www.linkedin.com/in/jayson-b-7a7418139/,DF Barnes,51-200,10M-100M,Canada,Manufacturing,Maximize Savings and Performance,Difficulty keeping up with evolving data security regulations,Risk and compliance management,We do not currently use any AWS solutions,"Yes, by email",TRUE,FALSE,FALSE,FALSE,Gautam,Coulter Software,
Kelly,Wotton,kwotton@renfrewhosp.com,16134324851,"Director, Information Technology",https://www.linkedin.com/in/kelly-wotton-a4970114/,Renfrew Victoria Hospital,201-500,10M-100M,Canada,Healthcare / Medical,Maximize Savings and Performance,Difficulty keeping up with evolving data security regulations,Data accessibility and storage,We do not currently use any AWS solutions,"Yes, by email",TRUE,FALSE,FALSE,FALSE,Subbu,,
Stephane,Lapierre,stephane.lapierre@ver-mac.com,14186709581,Director of IT Innovation,https://www.linkedin.com/in/st%C3%A9phane-lapierre-281b6452/?f_s=true,Ver-Mac,201-500,10M-100M,Canada,Manufacturing,Maximize Savings and Performance,Limited scalability with our current data infrastructure,Risk and compliance management,"AWS Security services (IAM, GuardDuty, etc.)","Yes, by email",TRUE,FALSE,FALSE,TRUE,Subbu,,Asked to reach out next year
Ovi,Crisan,ovi@gopineapple.com,16474003427,Senior Director IT,https://www.linkedin.com/in/ovicrisan/?f_s=true,Pineapple,51-200,10M-100M,Canada,Finance,Maximize Savings and Performance,Difficulty keeping up with evolving data security regulations,Cost control,We do not currently use any AWS solutions,Not at this time,TRUE,FALSE,FALSE,FALSE,Sakal,,
Rahul,Suresh,rsuresh@haliburton.net,15144308552,Director of Technology IT,https://www.linkedin.com/in/rahul-suresh-05197156/?f_s=true,"Haliburton International Foods, Inc.",201-500,10M-100M,Canada,Manufacturing,Maximize Savings and Performance,Limited scalability with our current data infrastructure,Resource provisioning,We do not currently use any AWS solutions,Not at this time,TRUE,FALSE,FALSE,FALSE,Sakal,,
Anup,Bhulabhai,abhulabhai@neptuneterminals.com,16043074692,Director of Information Technology,https://www.linkedin.com/in/anup-bhulabhai-457a34a/,Neptune Terminals,201-500,10M-100M,Canada,Transportation and Logistics,Maximize Savings and Performance,Cost and complexity of maintaining legacy solutions,Data accessibility and storage,We do not currently use any AWS solutions,Not at this time,TRUE,FALSE,FALSE,TRUE,Gautam,,"does not remember the survey, No intent of moving to AWS or cloud at this time just 1 termina on site stayed on the call as bought products from ingram through a supplier"
Hugo,Morin,hugo.morin@itaq.ca,14188561110,Director Digital Transformation and Technology Department,https://www.itaq.ca/a-propos-de-litaq/presentation/equipe-de-direction-de-litaq/,Institut de technologie agroalimentaire du Quebec,201-500,10M-100M,Canada,Education,Maximize Savings and Performance,Significant delays with deploying new users and workloads,Cost control,We do not currently use any AWS solutions,"Yes, by email",TRUE,FALSE,FALSE,FALSE,Gautam,,`;

export const CSV_DATA_DEMO = `First Name,Last Name,Email,Phone Number,Title,Company,Revenue,Industry,Internal Lead,Partner,Lead Notes / AWS Status
Davin,Hill,dhill@slmhc-demo.on.ca,1-807-737-****,Director of IT,Sioux Lookout Meno Ya Win Health,10M-100M,Healthcare,Sakal,HabileLabs,No current AWS usage
Jivan,Raj,jraj@olympic-demo.ca,1-416-324-****,IT Director,Canadian Olympic Committee,10M-100M,Non-Profit,Sakal,HabileLabs,Uses AWS Lambda
Moheb,Kladios,m.kladios@cvc-test.ca,1-416-918-****,CIO,Credit Valley Conservation,10M-100M,Non-Profit,Sakal,HabileLabs,No current AWS usage
Dan,Mizra,dmizra@ontariospca-demo.ca,1-416-618-****,"Director, IT Systems",Ontario SPCA & Humane Society,10M-100M,Non-Profit,Sakal,HabileLabs,Uses AWS Lambda
Jon,Gagne,jgagne@sbi-demo.com,1-418-575-****,Director of IT,SBI Stove Builder Int.,10M-100M,Manufacturing,Sakal,HabileLabs,Uses Amazon S3
Raz,Angel,rangel@signifi-demo.com,1-647-708-****,Director of IT,"Signifi Solutions, Inc.",10M-100M,Technology,Subbu,Ingeno,No current AWS usage
Mo,Bakri,mbakri@entegrus-test.com,1-519-871-****,Director of IT,Entegrus,10M-100M,Utility / Energy,Subbu,Ingeno,No current AWS usage
Terry,Aubin,t.aubin@mirabel-demo.ca,1-450-475-****,Head of IT Admin,Ville De Mirabel,10M-100M,Government,Subbu,Ingeno,No current AWS usage
Max,Goulet,mgoulet@ferique-demo.com,1-514-649-****,VP Technologies,FERIQUE,10M-100M,Finance,Subbu,Ingeno,Uses Amazon S3
Jean,L'Heureux,jlheuri@fishtank-demo.ca,1-418-925-****,Director of Technology,Fishtank Consulting,1-10M,Technology,Subbu,Ingeno,No current AWS usage
Kris,Bowie,kbowie@unitedway-demo.ca,1-613-277-****,Chief Info & Tech Officer,United Way East Ontario,10M-100M,Non-Profit,Gautam,Coulter Software,No current AWS usage
Neil,Hopson,nhopson@dale-demo.on.ca,1-519-671-****,Director HR & IS,Dale Brain Injury Services,10M-100M,Healthcare,Gautam,Coulter Software,No current AWS usage
Murthy,Challa,mchalla@bulldog-demo.com,1-800-665-****,CIO,"Bulldog Bag, LTD",10M-100M,Manufacturing,Gautam,Coulter Software,No current AWS usage
Mauro,Bricen,mbricen@organigram-demo.ca,1-647-409-****,Director of IT Ops,Organigram Global,100M-500M,Manufacturing,Gautam,Coulter Software,Other AWS usage
Etien,Bedard,ebedard@parl-demo.gc.ca,1-613-944-****,"Director, Digital Strategy",House Of Commons Canada,100M-500M,Government,Gautam,Coulter Software,No current AWS usage
Cat,Petria,cpetria@tempo-demo.io,1-514-434-****,Director of IT,Tempo Software,10M-100M,Technology,Sakal,—,All AWS solutions
Serge,Tremblay,stremblay@inrs-demo.ca,1-418-865-****,Director Info Resources,Institut National Recherche,1-10M,Education,Sakal,—,Uses Amazon EC2
Alan,Boivin,aboivin@cogiweb-test.com,1-418-880-****,Director ICT,COGIWEB,10M-100M,Technology,Subbu,Ingeno,No current AWS usage
Matt,Pointe,mpointe@wildblue-demo.com,1-418-343-****,Head of IT,Quebec Wild Blueberry Grp,10M-100M,Manufacturing,Subbu,Ingeno,No current AWS usage
Remy,Cote,rcote@entrepots-demo.ca,1-450-435-****,IT Director,AB Warehouse,1-10M,Logistics,Gautam,Coulter Software,Uses Azure
Jay,Byrne,jbyrne@dfbarnes-demo.com,1-709-726-****,"Director, ICT",DF Barnes,10M-100M,Manufacturing,Gautam,Coulter Software,No current AWS usage
Kelly,Wotton,kwotton@renfrew-demo.com,1-613-432-****,"Director, IT",Renfrew Victoria Hospital,10M-100M,Healthcare,Subbu,—,No current AWS usage
Steph,Pier,spier@vermac-demo.com,1-418-670-****,Director IT Innovation,Ver-Mac,10M-100M,Manufacturing,Subbu,—,Uses AWS Security (Asked to reach out next year)
Ovi,Crisan,ocrisan@pineapple-demo.com,1-647-400-****,Senior Director IT,Pineapple,10M-100M,Finance,Sakal,—,No current AWS usage
Rahul,Suresh,rsuresh@haliburton-demo.net,1-514-443-****,Director of Technology,Haliburton Int. Foods,10M-100M,Manufacturing,Sakal,—,No current AWS usage
Anup,Bhai,abhai@neptune-demo.com,1-604-307-****,Director of IT,Neptune Terminals,10M-100M,Logistics,Gautam,—,No intent to move to Cloud
Hugo,Morin,hmorin@itaq-demo.ca,1-418-885-****,Director Digital Trans.,Institut tech. agroalimentaire,10M-100M,Education,Gautam,—,No current AWS usage`;
